[package]
name = "mutate"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
tempfile = "3.10"

[target.'cfg(windows)'.dependencies]
winreg = "0.50"
